// src/constants/analytics.ts

// 🔹 Lista de analíticos Dahua (copiado da sua lista)
export const DAHUA_ANALYTICS = [
  "VideoMotion",
  "SmartMotionHuman",
  "SmartMotionVehicle",
  "VideoLoss",
  "VideoBlind",
  "AlarmLocal",
  "CrossLineDetection",
  "CrossRegionDetection",
  "LeftDetection",
  "TakenAwayDetection",
  "VideoAbnormalDetection",
  "FaceDetection",
  "AudioMutation",
  "AudioAnomaly",
  "VideoUnFocus",
  "WanderDetection",
  "RioterDetection",
  "ParkingDetection",
  "MoveDetection",
  "StorageNotExist",
  "StorageFailure",
  "StorageLowSpace",
  "AlarmOutput",
  "MDResult",
  "HeatImagingTemper",
  "CrowdDetection",
  "FireWarning",
  "FireWarningInfo",
] as const;

// 🔹 Lista de analíticos Hikvision (copiado da sua lista)
export const HIKVISION_ANALYTICS = [
  "ADAS",
  "ADASAlarm",
  "AID",
  "ANPR",
  "AccessControllerEvent",
  "CDsStatus",
  "DBD",
  "GPSUpload",
  "HFPD",
  "IO",
  "IOTD",
  "LES",
  "LFPD",
  "PALMismatch",
  "PIR",
  "PeopleCounting",
  "PeopleNumChange",
  "Standup",
  "TMA",
  "TMPA",
  "VMD",
  "abnormalAcceleration",
  "abnormalDriving",
  "advReachHeight",
  "alarmResult",
  "attendance",
  "attendedBaggage",
  "audioAbnormal",
  "audioexception",
  "behaviorResult",
  "blindSpotDetection",
  "cardMatch",
  "changedStatus",
  "collision",
  "containerDetection",
  "crowdSituationAnalysis",
  "databaseException",
  "defocus",
  "diskUnformat",
  "diskerror",
  "diskfull",
  "driverConditionMonitor",
  "emergencyAlarm",
  "faceCapture",
  "faceSnapModeling",
  "facedetection",
  "failDown",
  "faultAlarm",
  "fielddetection",
  "fireDetection",
  "fireEscapeDetection",
  "flowOverrun",
  "framesPeopleCounting",
  "getUp",
  "group",
  "hdBadBlock",
  "hdImpact",
  "highHDTemperature",
  "highTempAlarm",
  "hotSpare",
  "illaccess",
  "ipcTransferAbnormal",
  "ipconflict",
  "keyPersonGetUp",
  "leavePosition",
  "linedetection",
  "loitering",
  "lowHDTemperature",
  "mixedTargetDetection",
  "modelError",
  "nicbroken",
  "nodeOffline",
  "nonPoliceIntrusion",
  "overSpeed",
  "overtimeTarry",
  "parking",
  "peopleNumChange",
  "peopleNumCounting",
  "personAbnormalAlarm",
  "personDensityDetection",
  "personQueueCounting",
  "personQueueDetection",
  "personQueueRealTime",
  "personQueueTime",
  "playCellphone",
  "pocException",
  "poe",
  "policeAbsent",
  "radarAlarm",
  "radarFieldDetection",
  "radarLineDetection",
  "radarPerimeterRule",
  "radarTargetDetection",
  "radarVideoDetection",
  "raidException",
  "rapidMove",
  "reachHeight",
  "recordCycleAbnormal",
  "recordException",
  "regionEntrance",
  "regionExiting",
  "retention",
  "rollover",
  "running",
  "safetyHelmetDetection",
  "scenechangedetection",
  "sensorAlarm",
  "severeHDFailure",
  "shelteralarm",
  "shipsDetection",
  "sitQuietly",
  "smokeAndFireDetection",
  "smokeDetection",
  "softIO",
  "spacingChange",
  "sysStorFull",
  "takingElevatorDetection",
  "targetCapture",
  "temperature",
  "thermometry",
  "thirdPartyException",
  "toiletTarry",
  "tollCodeInfo",
  "tossing",
  "unattendedBaggage",
  "vehicleMatchResult",
  "vehicleRcogResult",
  "versionAbnormal",
  "videoException",
  "videoloss",
  "violationAlarm",
  "violentMotion",
  "yardTarry",
  "AccessControllerEvent", // repetido na doc, mantido conforme enviado
  "IDCardInfoEvent",
  "FaceTemperatureMeasurementEvent",
  "QRCodeEvent",
  "CertificateCaptureEvent",
  "UncertificateCompareEvent",
  "ConsumptionAndTransactionRecordEvent",
  "ConsumptionEvent",
  "TFS",
  "TransactionRecordEvent",
  "HealthInfoSyncQuery",
  "SetMealQuery",
  "ConsumptionStatusQuery",
  "certificateRevocation",
  "humanBodyComparison",
  "regionTargetNumberCounting",
] as const;

// 🔹 Tipos (opcional, mas útil p/ tipagem)
export type DahuaAnalytic = (typeof DAHUA_ANALYTICS)[number];
export type HikvisionAnalytic = (typeof HIKVISION_ANALYTICS)[number];

// 🔹 Map para buscar por fabricante
export const ANALYTICS_BY_MANUFACTURER: Record<string, readonly string[]> = {
  dahua: DAHUA_ANALYTICS,
  hikvision: HIKVISION_ANALYTICS,
};

// Sugestões padrão (equivalentes ao que você usava no backend)
export const DEFAULT_ANALYTICS_BY_MANUFACTURER: Record<string, string[]> = {
  dahua: ["FaceDetection", "CrossLineDetection", "CrossRegionDetection"],
  hikvision: ["faceCapture", "VMD"],
};
